name: Build muenvsubst
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: ./build.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: muenvsubst
          path: dist/muenvsubst

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/muenvsubst
