name: Build muenvsubst
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
            IMAGE_NAME=muenvsubst-build

            docker build --progress plain --tag ${IMAGE_NAME} .

            id=$(docker create ${IMAGE_NAME})
            mkdir -p dist
            docker cp $id:/build/muenvsubst .
            docker rm -v $id

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: muenvsubst
          path: muenvsubst

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: muenvsubst
